/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import Modelo.Cama;
import Modelo.Habitacion;
import Modelo.Ubicacion;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
* @author FlorBarrera
 */
public class vCama extends javax.swing.JInternalFrame {

Controlador controlador;
ArrayList<Ubicacion> ubicaciones;
ArrayList<Habitacion> habitaciones;
ArrayList<Cama> camas;
    
    public vCama() throws SQLException {
        initComponents();
        controlador = new Controlador();
        ubicaciones = new ArrayList<Ubicacion>();
        habitaciones = new ArrayList<Habitacion>();
        camas = new ArrayList<Cama>();
        
        controlador.llenarTablaCama(tablaCama);
        
        habitaciones = controlador.llenarComboHabitacion();
        ubicaciones = controlador.llenarComboUbicacion();
        for (int i = 0; i < habitaciones.size(); i++) {
            cbHabitacion.addItem(habitaciones.get(i).getNumero()+" " + ubicaciones.get(i).getHospital()+" "+ubicaciones.get(i).getNombreSala());
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCama = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        cbEstado = new javax.swing.JComboBox<>();
        cbHabitacion = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        tablaCama.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaCama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCamaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCama);

        jLabel1.setText("Numero de Cama:");

        jLabel2.setText("Estado:");

        jLabel3.setText("Habitación:");

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Estado Cama...", "Disponible", "No Disponible" }));

        cbHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la Habitación..." }));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNumero)
                                            .addComponent(cbEstado, 0, 149, Short.MAX_VALUE))
                                        .addGap(165, 165, 165)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1)
                                            .addComponent(btnEliminar)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(btnAgregar)))
                        .addGap(0, 164, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Cama cama = new Cama();
        Habitacion habitacion = new Habitacion();
        Ubicacion ubicacion = new Ubicacion();
        
        
        cama.setNumero(Integer.parseInt(txtNumero.getText()));
        
        
        int idUbicacion = ubicaciones.get(cbHabitacion.getSelectedIndex()-1).getIdUbicacion();
        String hospital = ubicaciones.get(cbHabitacion.getSelectedIndex()-1).getHospital();
        String nombreSala = ubicaciones.get(cbHabitacion.getSelectedIndex()-1).getNombreSala();
        
        int idHabitacion = habitaciones.get(cbHabitacion.getSelectedIndex()-1).getIdHabitacion();
        int numero = habitaciones.get(cbHabitacion.getSelectedIndex()-1).getNumero();

        
        ubicacion.setIdUbicacion(idUbicacion);
        ubicacion.setHospital(hospital);
        ubicacion.setNombreSala(nombreSala);
      
        habitacion.setIdHabitacion(idHabitacion);
        habitacion.setNumero(numero);
        habitacion.setUbicacion(ubicacion);
        
        cama.setHabitacion(habitacion);
        
        if (cbEstado.getSelectedIndex()!=0){
            cama.setEstado(cbEstado.getSelectedItem().toString());
            controlador.insertarCama(cama, habitacion, tablaCama);}
            else {
            JOptionPane.showMessageDialog(null, "Seleccione Estado Cama");
        }
        
        //controlador.insertarCama(cama, habitacion, tablaCama);
//        if ((cbEstado.getSelectedIndex()-1)==1){
//            cama.setEstado("Disponible");                 
//                if ((cbEstado.getSelectedIndex()-1)==2)
//                    cama.setEstado("No Disponible");
//                else JOptionPane.showMessageDialog(null, "Seleccione el Estado");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Cama cama = new Cama();
        int row = tablaCama.getSelectedRow();
        String id = tablaCama.getValueAt(row, 3).toString();
        cama.setIdCama(Integer.parseInt(id));
        
        controlador.eliminarCama(cama, tablaCama);
        
        limpiarCampos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaCamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCamaMouseClicked
        int row = tablaCama.getSelectedRow();
        String numero = tablaCama.getValueAt(row, 4).toString();
        //String ubicacion = tablaHabitacion.getValueAt(row, 2).toString();
        
        txtNumero.setText(numero);
        //txtNombre.setText(nombre);
    }//GEN-LAST:event_tablaCamaMouseClicked
        
public void limpiarCampos(){
    
    txtNumero.setText("");

}    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbHabitacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCama;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
