/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import Modelo.Cama;
import Modelo.Habitacion;
import Modelo.Ubicacion;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
* @author FlorBarrera
 */
public class vCama extends javax.swing.JInternalFrame {

Controlador controlador;
ArrayList<Ubicacion> ubicaciones;
ArrayList<Habitacion> habitaciones;
ArrayList<Cama> camas;
Ubicacion u;
Habitacion h;
    public vCama() throws SQLException {
         initComponents();
        controlador = new Controlador();
        ubicaciones = new ArrayList<Ubicacion>();
        habitaciones = new ArrayList<Habitacion>();
        camas = new ArrayList<Cama>();
        u = new Ubicacion();
        h = new Habitacion();
        controlador.llenarTablaCama(tablaCama);
        habitaciones = controlador.llenarComboHabitacion();
        ubicaciones = controlador.llenarComboUbicacion();

         
        for (int i = 0; i < habitaciones.size(); i++) {
            u=habitaciones.get(i).getUbicacion();
            //System.out.println("add; " + habitaciones.get(i).getNumero()+" " + ubicaciones.get(i).getHospital()+" "+ubicaciones.get(i).getNombreSala());
            System.out.println("add; " + habitaciones.get(i).getNumero()+" " + u.getHospital()+" "+u.getNombreSala());
            cbHabitacion.addItem(habitaciones.get(i).getNumero()+" " + u.getHospital()+" "+u.getNombreSala());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCama = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        cbEstado = new javax.swing.JComboBox<>();
        cbHabitacion = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAgregar1 = new javax.swing.JButton();

        tablaCama.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaCama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCamaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCama);

        jLabel1.setText("Numero de Cama:");

        jLabel2.setText("Estado:");

        jLabel3.setText("Habitación:");

        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroKeyTyped(evt);
            }
        });

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Estado Cama...", "Disponible", "No Disponible" }));

        cbHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la Habitación..." }));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnAgregar1.setText("Liberar");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNumero)
                                        .addComponent(cbEstado, 0, 149, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(btnAgregar)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregar1)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(0, 168, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnAgregar1)
                    .addComponent(btnEliminar)
                    .addComponent(jButton1))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Cama cama = new Cama();
        Habitacion habitacion = new Habitacion();
        Ubicacion ubicacion = new Ubicacion();
        
        
//        int idUbicacion = ubicaciones.get(cbHabitacion.getSelectedIndex()-1).getIdUbicacion();
//        String hospital = ubicaciones.get(cbHabitacion.getSelectedIndex()-1).getHospital();
//        String nombreSala = ubicaciones.get(cbHabitacion.getSelectedIndex()-1).getNombreSala();
//        Ubicacion.setIdUbicacion(idUbicacion);
//        ubicacion.setHospital(hospital);
//        ubicacion.setNombreSala(nombreSala);
//        JOptionPane.showMessageDialog(null, "hospital:"+hospital);
//        JOptionPane.showMessageDialog(null, "nombre sala:"+nombreSala);
        
        int idHabitacion = habitaciones.get(cbHabitacion.getSelectedIndex()-1).getIdHabitacion();
        int numero = habitaciones.get(cbHabitacion.getSelectedIndex()-1).getNumero();
        habitacion.setIdHabitacion(idHabitacion);
        habitacion.setNumero(numero);
        //habitacion.setUbicacion(ubicacion);
//        JOptionPane.showMessageDialog(null, "habitacion seleccionada:"+idHabitacion);
//        JOptionPane.showMessageDialog(null, "numero de habitacion:"+numero);

        cama.setNumero(Integer.parseInt(txtNumero.getText()));
        cama.setEstado(cbEstado.getSelectedItem().toString());
        cama.setHabitacion(habitacion);
                       
        if(Integer.parseInt(txtNumero.getText())<=0){
        JOptionPane.showMessageDialog(null, "El numero de cama no puede ser igual o menos a cero");
        }else{
        if (cbEstado.getSelectedIndex()!=0){
            
            controlador.insertarCama(cama, habitacion, tablaCama);}
            else {
            JOptionPane.showMessageDialog(null, "Seleccione Estado Cama");
        }
        }
        
        //controlador.insertarCama(cama, habitacion, tablaCama);
//        if ((cbEstado.getSelectedIndex()-1)==1){
//            cama.setEstado("Disponible");                 
//                if ((cbEstado.getSelectedIndex()-1)==2)
//                    cama.setEstado("No Disponible");
//                else JOptionPane.showMessageDialog(null, "Seleccione el Estado");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Cama cama = new Cama();
        int row = tablaCama.getSelectedRow();
        String id = tablaCama.getValueAt(row, 3).toString();
        cama.setIdCama(Integer.parseInt(id));
        
        controlador.eliminarCama(cama, tablaCama);
        
        limpiarCampos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaCamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCamaMouseClicked
        int row = tablaCama.getSelectedRow();
        String numero = tablaCama.getValueAt(row, 4).toString();
        if(tablaCama.getValueAt(row, 5)=="Disponible"){
        this.btnAgregar1.setVisible(false);
        //JOptionPane.showMessageDialog(null, "el boton esta dispo");
        }else{
        this.btnAgregar1.setVisible(true);
        //JOptionPane.showMessageDialog(null, "el boton no esta dispo");
        }
        //JOptionPane.showMessageDialog(null, tablaCama.getValueAt(row, 5));
        //String ubicacion = tablaHabitacion.getValueAt(row, 2).toString();
        
        txtNumero.setText(numero);
        //txtNombre.setText(nombre);
    }//GEN-LAST:event_tablaCamaMouseClicked

    private void txtNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyTyped
         //Integer.parseInt(txtNumero.getText());
        System.out.println("tecla presionada:  "+evt.getKeyChar());
        char a = evt.getKeyChar();
        boolean valido = false;
          if(txtNumero.getText().length() ==0 )
    {
        if (a == '-' ||  a == '0' ) {
            JOptionPane.showMessageDialog(null, "Tiene que ingresar numeros positivos mayores a cero (0).");

        } else if (a > '0' && a <= '9') {
            valido = true;
        }
        if (!valido) {
            evt.consume();
        }        // TODO add your handling code here:
    }
    }//GEN-LAST:event_txtNumeroKeyTyped

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        Cama cama = new Cama();
        int row = tablaCama.getSelectedRow();
        //JOptionPane.showMessageDialog(null, tablaCama.getValueAt(row, 5));
        
        String id = tablaCama.getValueAt(row, 3).toString();
        cama.setIdCama(Integer.parseInt(id));
        
        controlador.liberarCama(cama, tablaCama);
    }//GEN-LAST:event_btnAgregar1ActionPerformed
        
public void limpiarCampos(){
    
    txtNumero.setText("");

}    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbHabitacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCama;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
